version: '3'

services:
  db:
    image: mysql:8.0.30
    container_name: mysql_8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=docker_init_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=main_user
      - MYSQL_PASSWORD=main_pass
    ports: 
      - 33060:3306
    volumes: 
      - local_dbdata:/var/lib/mysql
      - .my.cnf:/etc/mysql/my.cnf
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  local_dbdata:

networks:
  default:
      name: db-network
