services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports: 
      - 6380:6379
    volumes: 
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:

networks:
  default:
    name: redis-net
