# Use postgres/example user/password credentials
services:

  db:
    image: timescale/timescaledb-ha:pg16
    container_name: timescale
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      #POSTGRES_USER: postgres (optional)
      #POSTGRES_DB: postgres (optional)
    ports:
      - 5432:5432
