version: "3.3"

services:
  traefik:
    image: "traefik:v2.8"
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443" # new
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # new
      # - "--certificatesresolvers.myresolver.acme.email=rajeshchaudhary@neputer.com" # new
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # new
    ports:
      - "80:80"
      - "8080:8080"
      # - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./letsencrypt:/letsencrypt" # new
