services:
  typesense:
    image: typesense/typesense:27.1
    container_name: typesense
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    volumes:
      - typesense_data:/data
      - ./typesense_logs:/usr/local/var/log/typesense/
    ports:
      - 8108:8108
    restart: unless-stopped
volumes:
  typesense_data:
