version: '3.8'

services:
  uptime-kuma:
    restart: unless-stopped
    ports:
      - '3031:3001'
    volumes:
      - 'uptime-kuma:/app/data'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'

volumes:
  uptime-kuma:
    name: uptime-kuma_vol

networks:
  default:
    name: uptime-kuma-net